controller_list:
  - name: fake_Arm_controller
    type: $(arg execution_type)
    joints:
      - One_joint
      - Two_joint
      - Three_joint
      - Four_joint
initial:  # Define initial robot poses.
  - group: Arm
    pose: Home